// src/AssignmentTwo.java
public class AssignmentTwo {
    public static void main(String[] args) {
        AssignmentTwo app = new AssignmentTwo();
        app.partSeven();
    }

    // --- Part7: Import Ride History from File Demo ---
    public void partSeven() {
        System.out.println("=== Part7: Import Ride History from File Demo ===");

        // 1. Create ride (initial history is empty)
        Employee ferrisWheelOperator = new Employee(
                "Zhang San",
                25,
                "138-1234-5678",
                "EMP-001",
                "Ferris Wheel"
        );
        Ride ferrisWheel = new Ride("Ferris Wheel", 4, ferrisWheelOperator);

        // 2. Print history BEFORE import (should be empty)
        System.out.println("\n--- Ride History Before Import ---");
        ferrisWheel.printRideHistory();

        // 3. Import history from the file (generated by Part6)
        String importFilePath = "ride_history.txt";
        ferrisWheel.importHistoryFromFile(importFilePath);

        // 4. Print history AFTER import (should match the exported data)
        System.out.println("\n--- Ride History After Import ---");
        ferrisWheel.printRideHistory();
    }

    // Placeholder methods for other parts
    public void partThree() {}
    public void partFourA() {}
    public void partFourB() {}
    public void partFive() {}
    public void partSix() {}
}